// ============================================================
// Демо-данные для проекта "Свадьба Ивановых"
// ============================================================

export const DEMO_PROJECT = {
  id: 'demo',
  title: 'Свадьба Ивановых',
  type: 'event' as const,
  status: 'planning' as const,
  clientName: 'Иванов Алексей',
  startDate: '2026-04-15',
  endDate: '2026-04-17',
  budget: 350000,
  description: 'Свадебная съёмка: утро невесты, церемония в загсе, банкет в ресторане «Олимп».',
};

export const DEMO_CREW = [
  {
    id: 'c1',
    name: 'Сергей Волков',
    role: 'operator' as const,
    roleLabel: 'Оператор',
    phone: '+7 921 123-45-67',
    email: 'volkov@mail.ru',
    ratePerDay: 15000,
    avatar: null,
    competencies: ['Sony FX6', 'DJI RS3', 'Steadicam'],
    projectRole: 'Основная камера (A)',
    availability: 'free' as const,
  },
  {
    id: 'c2',
    name: 'Анна Кузнецова',
    role: 'operator' as const,
    roleLabel: 'Оператор',
    phone: '+7 911 234-56-78',
    email: 'anna.k@gmail.com',
    ratePerDay: 12000,
    avatar: null,
    competencies: ['Canon R5', 'Ronin', 'Дрон DJI Mini 3'],
    projectRole: 'Вторая камера (B) + дрон',
    availability: 'free' as const,
  },
  {
    id: 'c3',
    name: 'Михаил Петров',
    role: 'sound_engineer' as const,
    roleLabel: 'Звукорежиссёр',
    phone: '+7 905 345-67-89',
    email: 'petrov.sound@yandex.ru',
    ratePerDay: 10000,
    avatar: null,
    competencies: ['Zoom F6', 'Sennheiser MKH416', 'Петличка DPA'],
    projectRole: 'Звук: петличка + бум',
    availability: 'free' as const,
  },
  {
    id: 'c4',
    name: 'Дмитрий Орлов',
    role: 'assistant' as const,
    roleLabel: 'Ассистент',
    phone: '+7 999 456-78-90',
    email: 'orlov.d@mail.ru',
    ratePerDay: 5000,
    avatar: null,
    competencies: ['Свет', 'Grip', 'Транспорт'],
    projectRole: 'Ассистент + водитель',
    availability: 'tentative' as const,
  },
  {
    id: 'c5',
    name: 'Елена Смирнова',
    role: 'lighting_tech' as const,
    roleLabel: 'Осветитель',
    phone: '+7 912 567-89-01',
    email: 'elena.light@gmail.com',
    ratePerDay: 8000,
    avatar: null,
    competencies: ['Aputure 600d', 'Godox', 'Отражатели'],
    projectRole: 'Свет на церемонии и банкете',
    availability: 'free' as const,
  },
];

export const DEMO_EQUIPMENT = [
  {
    id: 'e1',
    category: 'camera' as const,
    categoryLabel: 'Камеры',
    name: 'Sony FX6',
    model: 'ILME-FX6V',
    serial: 'FX6-2024-001',
    status: 'on_shoot' as const,
    statusLabel: 'На проекте',
    ownership: 'owned' as const,
    assignedTo: 'Сергей Волков',
  },
  {
    id: 'e2',
    category: 'camera' as const,
    categoryLabel: 'Камеры',
    name: 'Canon EOS R5',
    model: 'R5 Mark II',
    serial: 'R5-2025-042',
    status: 'on_shoot' as const,
    statusLabel: 'На проекте',
    ownership: 'owned' as const,
    assignedTo: 'Анна Кузнецова',
  },
  {
    id: 'e3',
    category: 'lens' as const,
    categoryLabel: 'Объективы',
    name: 'Sony 24-70mm f/2.8 GM II',
    model: 'SEL2470GM2',
    serial: 'L-2470-018',
    status: 'on_shoot' as const,
    statusLabel: 'На проекте',
    ownership: 'owned' as const,
    assignedTo: 'Сергей Волков',
  },
  {
    id: 'e4',
    category: 'lens' as const,
    categoryLabel: 'Объективы',
    name: 'Canon RF 70-200mm f/2.8L',
    model: 'RF70-200',
    serial: 'L-7020-007',
    status: 'on_shoot' as const,
    statusLabel: 'На проекте',
    ownership: 'owned' as const,
    assignedTo: 'Анна Кузнецова',
  },
  {
    id: 'e5',
    category: 'lighting' as const,
    categoryLabel: 'Свет',
    name: 'Aputure 600d Pro',
    model: 'LS 600d Pro',
    serial: 'AP-600-003',
    status: 'on_shoot' as const,
    statusLabel: 'На проекте',
    ownership: 'owned' as const,
    assignedTo: 'Елена Смирнова',
  },
  {
    id: 'e6',
    category: 'lighting' as const,
    categoryLabel: 'Свет',
    name: 'Godox SL-200 III',
    model: 'SL200III',
    serial: 'GD-200-012',
    status: 'on_shoot' as const,
    statusLabel: 'На проекте',
    ownership: 'owned' as const,
    assignedTo: 'Елена Смирнова',
  },
  {
    id: 'e7',
    category: 'audio' as const,
    categoryLabel: 'Звук',
    name: 'Zoom F6',
    model: 'F6',
    serial: 'ZM-F6-009',
    status: 'on_shoot' as const,
    statusLabel: 'На проекте',
    ownership: 'owned' as const,
    assignedTo: 'Михаил Петров',
  },
  {
    id: 'e8',
    category: 'audio' as const,
    categoryLabel: 'Звук',
    name: 'Sennheiser MKH 416',
    model: 'MKH416-P48U3',
    serial: 'SN-416-005',
    status: 'on_shoot' as const,
    statusLabel: 'На проекте',
    ownership: 'owned' as const,
    assignedTo: 'Михаил Петров',
  },
  {
    id: 'e9',
    category: 'grip' as const,
    categoryLabel: 'Grip',
    name: 'DJI RS 3 Pro',
    model: 'RS3 Pro',
    serial: 'DJI-RS3-014',
    status: 'on_shoot' as const,
    statusLabel: 'На проекте',
    ownership: 'owned' as const,
    assignedTo: 'Сергей Волков',
  },
  {
    id: 'e10',
    category: 'camera' as const,
    categoryLabel: 'Камеры',
    name: 'DJI Mini 3 Pro',
    model: 'Mini 3 Pro',
    serial: 'DJI-M3P-021',
    status: 'on_shoot' as const,
    statusLabel: 'На проекте',
    ownership: 'owned' as const,
    assignedTo: 'Анна Кузнецова',
  },
];

export const DEMO_SHOOT_DAYS = [
  {
    id: 'sd1',
    date: '2026-04-15',
    title: 'Утро невесты',
    location: 'Квартира невесты, ул. Парковая 12',
    callTime: '08:00',
    wrapTime: '12:00',
    status: 'planned' as const,
    crew: ['c1', 'c2', 'c4'],
    scenes: [
      { id: 's1', order: 1, type: 'b_roll' as const, description: 'Детали: платье, туфли, букет, кольца', duration: 30 },
      { id: 's2', order: 2, type: 'interview' as const, description: 'Сборы невесты: макияж, причёска', duration: 60 },
      { id: 's3', order: 3, type: 'b_roll' as const, description: 'Портреты невесты у окна', duration: 20 },
      { id: 's4', order: 4, type: 'action' as const, description: 'Выход, встреча с женихом', duration: 15 },
    ],
  },
  {
    id: 'sd2',
    date: '2026-04-15',
    title: 'Церемония',
    location: 'ЗАГС Центрального района, Невский пр. 56',
    callTime: '13:00',
    wrapTime: '15:30',
    status: 'planned' as const,
    crew: ['c1', 'c2', 'c3', 'c4', 'c5'],
    scenes: [
      { id: 's5', order: 1, type: 'action' as const, description: 'Приезд, ожидание', duration: 20 },
      { id: 's6', order: 2, type: 'action' as const, description: 'Церемония бракосочетания', duration: 30 },
      { id: 's7', order: 3, type: 'action' as const, description: 'Выход, поздравления, фото с гостями', duration: 30 },
      { id: 's8', order: 4, type: 'b_roll' as const, description: 'Прогулка: Летний сад, набережная', duration: 60 },
    ],
  },
  {
    id: 'sd3',
    date: '2026-04-15',
    title: 'Банкет',
    location: 'Ресторан «Олимп», ул. Ломоносова 14',
    callTime: '17:00',
    wrapTime: '23:00',
    status: 'planned' as const,
    crew: ['c1', 'c2', 'c3', 'c4', 'c5'],
    scenes: [
      { id: 's9', order: 1, type: 'b_roll' as const, description: 'Декорации зала до прихода гостей', duration: 20 },
      { id: 's10', order: 2, type: 'action' as const, description: 'Встреча молодожёнов, первый танец', duration: 30 },
      { id: 's11', order: 3, type: 'action' as const, description: 'Тосты, поздравления, конкурсы', duration: 120 },
      { id: 's12', order: 4, type: 'action' as const, description: 'Торт, букет, завершение', duration: 30 },
    ],
  },
];

export const DEMO_SET_PLANS = [
  {
    id: 'sp1',
    name: 'Церемония — расстановка камер',
    shootDay: 'Церемония',
    scene: 'Церемония бракосочетания',
    elements: 4,
    updatedAt: '2026-03-28',
  },
  {
    id: 'sp2',
    name: 'Банкет — свет + камеры',
    shootDay: 'Банкет',
    scene: 'Декорации зала',
    elements: 7,
    updatedAt: '2026-03-27',
  },
];

// Helpers
export const AVAILABILITY_LABELS: Record<string, string> = {
  free: 'Свободен',
  busy: 'Занят',
  tentative: 'Под вопросом',
};

export const AVAILABILITY_COLORS: Record<string, string> = {
  free: 'green',
  busy: 'red',
  tentative: 'amber',
};

export const SCENE_TYPE_LABELS: Record<string, string> = {
  interview: 'Интервью',
  b_roll: 'B-roll',
  stand_up: 'Стендап',
  dialogue: 'Диалог',
  action: 'Действие',
  other: 'Другое',
};
